<?php

// CLI part of sphinx module

//$db = new db ();
//$db->connect();

/*
function sphinx_create_master_index () {
    $command = 'sudo indexer --all --rotate --quiet';
    return $res = cos_exec($command, array ('silence' => true));
}


mainCli::setCommand('sphinx', array(
    'description' => "Commands for creating sphinx indexes",
));

mainCli::setOption('sphinx_create_master_index', array(
    'long_name'   => '--create-index',
    'description' => 'Will create a master index of all indexes specified in sphinx.conf',
    'action'      => 'StoreTrue'
));


//$db->getNumRows();

*/